### ISSUE TITLE
Allow to specify lock method while creating lock 

### ISSUE THREAD

**Issue by suhas-babyoye** [WoLpH/portalocker#10]
When using the first method mentioned in the examples here, http://portalocker.readthedocs.org/en/latest/usage.html#examples , the lock method is hard coded to the following in portalocker/utils.py:

    LOCK_METHOD = portalocker.LOCK_EX | portalocker.LOCK_NB

Instead of doing it that way, could we specify the lock method in the constructor? Or could it be determined based on whether the file is being used for read or write? This Lock object has the timeout functionality which is useful while opening files for reading(if they are locked for writing). But there is no need for LOCK_EX in 'r' mode. 

Please let me know if I missed something.

**Comment by WoLpH** [comment]
Version 0.5.5 now has support for a `flags` parameter to customize the locking :)

**Comment by suhas-babyoye** [comment]
Wow.. That was really fast :). Thanks.

**Comment by WoLpH** [comment]
The fix simple enough luckily, that helps :)
