### ISSUE TITLE
Doesn't work on Ubuntu 14.04, python 2.7.6?

### ISSUE THREAD

**Issue by vladiibine** [WoLpH/portalocker#11]
So I did this in one python console (the file already existed)

```
import portalocker as pl
f1 = open('./asdf', 'w')
pl.lock(f1, pl.LOCK_EX)
```

Then in another python console I did this

```
f1 = open('./asdf', 'w')
f1.write('zzzzzzzzzzzzzzzzfdffffffffffffffffffffffffff')
f1.close()
```

Then I do this in a bash console
```
$ cat ./asdf
zzzzzzzzzzzzzzzzfdffffffffffffffffffffffffff
```

Am I missing something about how this is supposed to work, or does it just not lock the file?

**Comment by WoLpH** [comment]
It does actually lock the file but on Ubuntu the code uses `flock()` internally, these locks are advisory which means there is no actual requirement to follow the locking.

Just execute the code from your console in 2 separate consoles and you will notice the locks but as far as I know there is no standard way to force locking on Ubuntu without changing your mounts to mandatory locking (with `-o mand`). But even these are known to be buggy unfortunately.
