### ISSUE TITLE
unsupported or invalid wheel

### ISSUE THREAD

**Issue by patkan** [WoLpH/portalocker#12]
When I try to install the version `0.5.7` from PyPi with pip `8.0.3` on Python `2.7` the installation of `portalocker` fails with the message `portalocker is in an unsupported or invalid wheel`.
This also happens on a travis-instance running Python `2.7`. Installation on a Python `3.4` instance however works without problem.
I suspect, without further inspection, that the wheel that you provide is not compatible with `2.7`.

**Comment by WoLpH** [comment]
Thanks for opening the issue, I have removed the wheel for now. It seems something went wrong while building it and I'll make sure to find out why before I upload a new one.

**Comment by WoLpH** [comment]
It seems to be related to forgetting to create a universal wheel... should be fixed now :)
