### ISSUE TITLE
supported versions on Pypi not current

### ISSUE THREAD

**Issue by obestwalter** [WoLpH/portalocker#13]
https://pypi.python.org/pypi/portalocker/0.5.7

    Programming Language :: Python :: 2.5
    Programming Language :: Python :: 2.6
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.1

vs .travis.yml:

    python:
        - '2.6'
        - '2.7'
        - '3.3'
        - '3.4'
        - '3.5'
        - 'pypy'
        - 'pypy3'

**Comment by WoLpH** [comment]
Thanks for the report, it's updated now :)
