### ISSUE TITLE
Read lock danger

### ISSUE THREAD

**Issue by petef4** [WoLpH/portalocker#14]
I was trying to make a read lock. I spotted from the docs that the default mode is append, which is a bit dangerous already, so I set the mode to read.

    In [208]: lock = portalocker.Lock(pathname, mode='r')

    In [209]: lock.acquire()
    ---------------------------------------------------------------------------
    IOError                                   Traceback (most recent call last)
    <ipython-input-209-394e97d7f4d5> in <module>()
    ----> 1 lock.acquire()

    /home/pforman/workspace/ipy27/lib/python2.7/site-packages/portalocker/utils.pyc in acquire(self, timeout, check_interval, fail_when_locked)
        105
        106         # Prepare the filehandle (truncate if needed)
    --> 107         fh = self._prepare_fh(fh)
        108
        109         self.fh = fh

    /home/pforman/workspace/ipy27/lib/python2.7/site-packages/portalocker/utils.pyc in _prepare_fh(self, fh, truncate)
        134         if truncate is not None:
        135             fh.seek(truncate)
    --> 136             fh.truncate(truncate)
        137
        138         return fh

    IOError: File not open for writing

Scary stuff. I see now that I also need to set `truncate=None`.

My problem would have been avoided by changing the default in `Lock.__init__()` to `truncate=None`.

The default Lock is effectively `mode='w'` but that is not obvious from `mode='a', truncate=0`. Indeed it will be surprising when `Lock(pathname, mode='a')` truncates your file and discards the contents you thought you were appending to.

I suggest that the default for mode be set to 'r' and truncate and flags default to None. The mode argument should then drive other defaulting, e.g. `flags is None and 'r' in mode and not '+' in mode => self.flags = LOCK_SH | LOCK_NB`. You might represent 'w' in the mode argument as 'W' in self.mode to maintain the truncate only after successful lock action; there are probably better ways of achieving that result.

Further to that I do not think there should be any truncate variables. The work done in `_prepare_fh` can be simplified to `fh.seek(0); fh.truncate()` if write mode was specified in `__init__`. Let the user do their own seek if they want do something other than overwrite or append.

**Comment by WoLpH** [comment]
That's a bit of a legacy issue unfortunately, while I agree with you that it's illogical I'm not a big fan of changing behaviour. This library is used by many others in many locations so besides introducing a new API I don't see a simple fix for the issue.

**Comment by petef4** [comment]
Well yes, it is the API that I find to be broken, in ways not present on the upstream ActiveState recipe. A read lock ought not to be concerned with truncate. Defaulting to an effective mode="w" when the signature has mode="a" violates POLA.

The standard way forward for you would be to bump the major version to indicate an API change. For my purposes I should stick to the lower level fcntl as I only need to run on Linux.

**Comment by WoLpH** [comment]
You're correct that it's not in the original ActiveState recipe but it was this way when I forked it a long time ago. The initial version found in this repo is how I found it at that time which means that there are people using in in this fashion. If people expect truncate but get append instead, applications will break in weird ways.

A major release bump can still be automatically installed if people simply specified `portalocker` as a requirement so that is definitely not an option. A new API to replace the old is an option but only with proper deprecation warnings for the old API.

**Comment by petef4** [comment]
Fair enough. Personally I consider it best practice to use explicit versioning in `requirements.txt`. I'll leave you to support your legacy dependents and move on.

**Comment by WoLpH** [comment]
It's definitely a valid point so I will add  an API with  a new and safer version.

**Comment by WoLpH** [comment]
The new version 1.0.0 fixes this issue and is therefore backwards incompatible with the old version.
