### ISSUE TITLE
Lock.acquire() does not have a matching release() method.

### ISSUE THREAD

**Issue by bwbeach** [WoLpH/portalocker#15]
My understanding is that the Python convention on locks is to have methods `acquire` and `release` for callers who want to manage releasing themselves, and `__enter__` and `__exit__` for those using the lock as a context manager.  portalocker.Lock has everything but `release`.

**Comment by WoLpH** [comment]
Thanks for the pull request, I'll push out a new release within a week with a big overhaul :)
