### ISSUE TITLE
Change the error message showed when the resource is locked

### ISSUE THREAD

**Issue by joanlopez** [WoLpH/portalocker#17]
Now I'm putting the exclusive code inside the next statement: `with portalocker.Lock():`.

It works well, but..

**Is there any way to change the given message when there's another process using the resource?**

Now I'm getting:

> [CRITICAL] Unhandled exception on Autosubmit: [Errno 11] Resource temporarily unavailable
>Traceback (most recent call last):
> ...
> ...
>AlreadyLocked: [Errno 11] Resource temporarily unavailable

Which is an ugly error and it is not intuitive for the users. Is it possible to show another message more friendly for the users? 

For example: "There is another instance of Autosubmit running this experiment, stop it before continue, please". Or something similar.

Surely you are agree with me that the traceback of all the Python error is useless and unpleasant for the users.

*Autosubmit is the tool that i'm developing.

Many thanks ;)

**Comment by the01** [comment]
Suround it with a `try: / catch AlreadyLocked:` block and write your message there?

**Comment by WoLpH** [comment]
As @the01 already said, you can simply catch the exception :)

```python
import portalocker


with portalocker.Lock():
    ...
except portalocker.AlreadyLocked:
    ...
    # raise your custom exception here
```
