### ISSUE TITLE
"portalocker is in an unsupported or invalid wheel"

### ISSUE THREAD

**Issue by martinunsal** [WoLpH/portalocker#21]
$ pip --no-cache-dir install portalocker
Collecting portalocker
  Downloading portalocker-0.6.0-py2.py3-none-any.whl
Installing collected packages: portalocker
portalocker is in an unsupported or invalid wheel
$ uname -a
Linux martin-desktop 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ 

0.6.0 seems to have been uploaded today so perhaps this is a bad release?

**Comment by martinunsal** [comment]
Perhaps related to https://github.com/WoLpH/portalocker/issues/12 ?
Also fyi:
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by WoLpH** [comment]
Very strange. It's an universal wheel so it should work everywhere.

I've removed it for the time being and will test it locally before
uploading it again. Thanks for the heads up.

**Comment by WoLpH** [comment]
For some reason I'm completely unable to reproduce the results... but... it seems this issue might have been caused by an outdated version of wheel on my system when building.

@martinunsal can you test the new wheel please?

**Comment by martinunsal** [comment]
Yes works great. Thanks for the awesome support.

$ ﻿⁠⁠⁠⁠﻿⁠⁠⁠⁠sudo pip install --upgrade portalocker
Collecting portalocker
  Downloading portalocker-0.6.1-py2.py3-none-any.whl
Installing collected packages: portalocker
  Found existing installation: portalocker 0.6.0
    Uninstalling portalocker-0.6.0:
      Successfully uninstalled portalocker-0.6.0
Successfully installed portalocker-0.6.1

**Comment by WoLpH** [comment]
Great to hear. Thanks :)
