### ISSUE TITLE
Link to docs into project header

### ISSUE THREAD

**Issue by techtonik** [WoLpH/portalocker#25]
Github allows to set URL in project header, and to make people read docs, it is better to redirect them there,

**Comment by WoLpH** [comment]
Yes, good idea. Seems I forgot to do that.

Done :)

**Comment by techtonik** [comment]
The only problem I noticed that docs and README are identical. )

**Comment by WoLpH** [comment]
Only partially. The docs also include the actual API.

I'm working on deploying releases on github as well so there is a single file which combines everything including the changelog. Some people prefer that format so they can easily incorporate the script.

**Comment by techtonik** [comment]
Some reusable code https://github.com/spyder-ide/loghub
