### ISSUE TITLE
AttributeError: 'msvcrt' object has no attribute 'LK_RLOCK'

### ISSUE THREAD

**Issue by junfenggood** [WoLpH/portalocker#36]
I try to use this package in Windows  OS, code is following:
```
import portalocker
import time

f = open("z:\\test1.txt","r")
portalocker.lock(f,portalocker.LOCK_SH)
f.write("hello, from  windows\n")
f.flush()
time.sleep(300)

f.close()

print "done"

```
But errors raised:
**Traceback (most recent call last):
  File "C:/Users/cifsuser10/Desktop/test.py", line 5, in <module>
    portalocker.lock(f,portalocker.LOCK_SH)
  File "C:\Python27\lib\site-packages\portalocker\portalocker.py", line 14, in lock
    mode = msvcrt.LK_RLOCK
AttributeError: 'module' object has no attribute 'LK_RLOCK'**

I check the mode msvcrt.
>>> dir(msvcrt)
**['CRT_ASSEMBLY_VERSION', 'LIBRARIES_ASSEMBLY_NAME_PREFIX', 'LK_LOCK', 'LK_NBLCK', 'LK_NBRLCK', 'LK_RLCK', 'LK_UNLCK', 'VC_ASSEMBLY_PUBLICKEYTOKEN', '__doc__', '__name__', '__package__', 'get_osfhandle', 'getch', 'getche', 'getwch', 'getwche', 'heapmin', 'kbhit', 'locking', 'open_osfhandle', 'putch', 'putwch', 'setmode', 'ungetch', 'ungetwch']**

No 'LK_RLOCK', but similar 'LK_RLCK', so, I think maybe this is a bug(Python 2.7.13, Windows Server 2012)

**Comment by WoLpH** [comment]
I've done a bit of research and I believe you're right. To make sure it won't break any existing code I'll edit it to allow for both. Can you try the develop branch? https://github.com/WoLpH/portalocker/tree/develop

**Comment by kain88-de** [comment]
For me this issue is fixed on develop.
