### ISSUE TITLE
Add pypiwin32 as dependency on setup.py

### ISSUE THREAD

**Issue by evandrocoan** [WoLpH/portalocker#38]
https://github.com/Preston-Landers/concurrent-log-handler/issues/3

**Comment by WoLpH** [comment]
If I understand the linked issue correctly, I need to check if the `pywin32` module can be imported and if not, `pypiwin32` should be installed?

Or should it always have `pypiwin32` as a dependency?

**Comment by WoLpH** [comment]
Also, it should be noted that the `concurrent-log-handler` uses one of the portalocker forks (this project was created in an attempt to unify them). Even if I fix this here it won't help for that project unless it switches from using `concurrent_log_handler.portalocker` to `portalocker`

**Comment by evandrocoan** [comment]
pypiwin32 and pywin32 are the same extension for Python for Windows, however pypiwin32 is an old version (220) of pywin32 extension (deprecated and not updated anymore) and pywin32 is the latest version (222).

However on the latest version of pywin32, they introduced a regression which breaks the installation: 

1. https://github.com/mhammond/pywin32/issues/1151 pypiwin32 version 222 - Failed to be installed

**Comment by evandrocoan** [comment]
> Even if I fix this here it won't help for that project unless it switches from using concurrent_log_handler.portalocker to portalocker

Yes, I was just pointing out it here so this problem does not happen for your direct users, because I lost some time fighting against this import error when running `tox` on Python 2.7 and 3.4

**Comment by WoLpH** [comment]
Thanks for the help, fixed on develop :)

**Comment by rayluo** [comment]
> pypiwin32 and pywin32 are the same extension for Python for Windows, however pypiwin32 is an old version (220) of pywin32 extension (deprecated and not updated anymore) and pywin32 is the latest version (222).

@evandrocoan , I read similar comment from [this StackOverflow Q&A](https://stackoverflow.com/questions/55918311/what-is-the-difference-between-pywin32-and-pypiwin32) too.
So, why didn't you just suggest @wolph to us `pywin32` rather than `pypiwin32` as a dependency? What gives?

**Comment by evandrocoan** [comment]
Because it was not working with my project which support older versions of python.

**Comment by WoLpH** [comment]
@evandrocoan I've switched out `pypiwin32 for `pywin32`. If there are issues with specific environments, can you tell me which ones so I can make an exception for those?

**Comment by evandrocoan** [comment]
Sure! I will get back when/if some problem show up.
