### ISSUE TITLE
PyWin32 as dependency?

### ISSUE THREAD

**Issue by lazuka13** [WoLpH/portalocker#39]
Hi!
Not sure if thats an issue, but I had to install pywin32 on Windows 10 myself, shouldn't it be listed somewhere or shouldn't it be installed in a portalocker installation process as a depedency? (I'm not quite good at writing setup.py files, so can't provide PR, but I beleve this problem can be solved by adding package name somewhere) 
Win 10, Python 3.6.4, virtualenv

**Comment by lazuka13** [comment]
Oh, I believe last closed issue was right about this problem.

**Comment by WoLpH** [comment]
It should install, can you show me the output of this script?

```python
import os
print(os.name)
```

It should show `nt`, if it does than I think it could be due to an old version of setuptools/pip/whatever. Just to be safe it could help to do a:
```
pip install -U pip setuptools
```

**Comment by lazuka13** [comment]
It does show `nt`, yes. I updated pip and setuptools to latest versions (10.0.1 and 39.1.0) on my main system interpreter (not venv) and tried to install portalocker - only one package was added, pywin32 wasn't installed. Pip output also doesn't say anything about pywin32. 
```
C:\Users\n_ame\Repositories\testing>pip install portalocker
Collecting portalocker
  Using cached https://files.pythonhosted.org/packages/0a/22/6a54021b020dd085d6cc03bf2243bbb7cf8808ac23be2db716780e7935c1/portalocker-1.2.0-py2.py3-none-any.whl
Installing collected packages: portalocker
Successfully installed portalocker-1.2.0
```

**Comment by WoLpH** [comment]
I found the issue, when using wheels the setup.py requirements are not used anymore so I'll need to update the system a bit. Thanks for letting me know :)

I'll push out a new release soon

**Comment by WoLpH** [comment]
The new release is online :)

**Comment by lazuka13** [comment]
That's great, thank you!
