### ISSUE TITLE
Passing arguments to underlying open()

### ISSUE THREAD

**Issue by aunsbjerg** [WoLpH/portalocker#42]
Right now, it doesn't seem to be possible to pass argument to `file.open()` when using the `with portalocker.Lock()` construct. For instance, I would like to be able to open a csv file with a specific newline argument, like so:

```python
with portalocker.Lock('test.csv', 'a', timeout=1, newline='') as csvfile:
    writer = csv.writer(csvfile)
```

I imagine that the `Lock()` constructor could take a `**kwargs` as the last arguments, which is then passed on to `file.open()`.

**Comment by WoLpH** [comment]
Good idea :)

Python 2 didn't have much in way of file open arguments but it's definitely useful now.
