### ISSUE TITLE
DOC: clarify "[portalocker is] an extended version of portalocker [...]"

### ISSUE THREAD

**Issue by jbrockmendel** [WoLpH/portalocker#43]
Nitpick asking for clarification in a couple places.  The one-line summary for this repo reads "An extended version of portalocker to lock files in Python using the with statement" and the one-line summary on pypi reads "Wraps the portalocker recipe for easy usage"

These make it sound like there is another package also called portalocker that this is wrapping.  can these be re-worded to clarify whether or not there exist two separate projects?

**Comment by WoLpH** [comment]
As is often the case with projects, this project has evolved quite a bit over time.

I think this library can be called the current standard as it is included in many distro's so anything mentioning wrapping and extended version has become obsolete.
