### ISSUE TITLE
tests directory

### ISSUE THREAD

**Issue by dbaio** [WoLpH/portalocker#44]
Hi.

Please, remove the `tests` directory of the distribution, it conflicts with other packages.

Thank you!

**Comment by WoLpH** [comment]
the exact reverse of a pull request a few years ago
https://github.com/WoLpH/portalocker/pull/8

I guess the better solution would be to move the tests to a subdirectory of portalocker but I'm not a fan of polluting the code directory with tests. Would renaming the directory to portalocker_tests be sufficient for you?

**Comment by dbaio** [comment]
sure, that helps.
thanks for your time.
