### ISSUE TITLE
The upsteam package pywin32 latest version 226 has an issue

### ISSUE THREAD

**Issue by rayluo** [WoLpH/portalocker#48]
Hi Rick,

Thanks for your work on PortALocker!

Its upsteam package pywin32's latest version 226 has an issue
https://github.com/mhammond/pywin32/issues/1439

which has ripple effects in all the downstream packages that currently , including popular Microsoft Azure SDK package https://github.com/Azure/azure-sdk-for-python/issues/8573

As the direct dependent of pywin32, would you consider to issue a temporary patch to pin `pywin32==225`?

CC: @chlowell

**Comment by WoLpH** [comment]
I'll do you one better, I've blacklisted the 226 release so a newer version will be installed automatically not never 226 :)

**Comment by rayluo** [comment]
Thanks Rick (@WoLpH ) for the super fast response! It would be great if you release this soon and then leave a message here so that @chlowell and I would know how to guide our end users.

**Comment by WoLpH** [comment]
@rayluo it's on pypi now :)
