### ISSUE TITLE
Depends on old and unsupported pytest-pep8

### ISSUE THREAD

**Issue by PureTryOut** [WoLpH/portalocker#51]
https://github.com/WoLpH/portalocker/blob/develop/setup.py#L32

pytest-pep8 hasn't seen a commit since 2015, and depends on pep8 which nowadays has been replaced for pycodestyle. Please update the tests to work with pycodestyle instead.

**Comment by WoLpH** [comment]
You're right, it's a bit out of date. Shouldn't matter all that much for linting but good to update in any case.

I've changed it to use flake8 instead
