### ISSUE TITLE
mode variable set but immediately overridden

### ISSUE THREAD

**Issue by naggie** [WoLpH/portalocker#52]
Hi @WoLpH ,

I've been reading the code to figure out how to write a lock checker. Whilst looking at it I found what looks like a mistake:

https://github.com/WoLpH/portalocker/blob/c34a48e5724b3874b7f5722a0192d213c81cf6c0/portalocker/portalocker.py#L51

```
            mode = win32con.LOCKFILE_EXCLUSIVE_LOCK
            if flags & constants.LOCK_NB:
                mode |= win32con.LOCKFILE_FAIL_IMMEDIATELY

            if flags & constants.LOCK_NB:
                mode = msvcrt.LK_NBLCK
            else:
                mode = msvcrt.LK_LOCK
```

It seems that mode will always be set to `msvcrt.LK_NBLCK` or `mode = msvcrt.LK_LOCK` making the first 3 lines in the snippet redundant.

Are the assignments supposed to set a bit instead of the entire variable? If not, assuming the 2 methods have the same affect, should the first 3 lines just be removed?

Thanks!
Callan

**Comment by naggie** [comment]
Ah, looking at the documentation for [mscvrt](https://docs.python.org/3.8/library/msvcrt.html) it seems that the second `mode` setting is valid as the code uses `msvcrt.locking` instead of `win32file.LockFileEx`.

I'll make a PR, please merge it if you agree.

**Comment by WoLpH** [comment]
The new release is online. Thank you for the help!

**Comment by naggie** [comment]
Great, no problem. Thanks!
