### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by MMK21Hub** [WoLpH/portalocker#55]
If I have a file that is:
``` python
import portalocker
```
It gives a ModuleNotFoundError:
```
No module named 'portalocker'
```

**Comment by WoLpH** [comment]
Sounds like you don't have portalocker installed in that case. Installing could help

**Comment by MMK21Hub** [comment]
Haha. I have done `pip install portalocker`.

**Comment by WoLpH** [comment]
My guess would be that you've installed it for a different python version, some python installations don't come with pip which cause these weird issues.

Try this: `python -m pip install -U portalocker`

**Comment by MMK21Hub** [comment]
The command outputs:
```
Requirement already up-to-date: portalocker in c:\python27\lib\site-packages (1.7.0)
Requirement already satisfied, skipping upgrade: pywin32!=226; platform_system == "Windows" in c:\python27\lib\site-packages (from portalocker) (228)
```

and the issue still persists.

**Comment by WoLpH** [comment]
Do you have a local file named `portalocker` by any chance? Something like that could cause these issues

**Comment by MMK21Hub** [comment]
No possibly problematic folder names. Even running it from the command line gives an error. However, in Python 2 it works fine.

**Comment by WoLpH** [comment]
You can look at the output from importlib, perhaps it sheds a little light as to what is being imported:
```python
import importlib
print(importlib.util.find_spec('portalocker'))
```

**Comment by MMK21Hub** [comment]
It doesn't look like that helped much:
```
========================= RESTART: D:/!TEMP/fsgrb.py =========================
None
```

**Comment by WoLpH** [comment]
Well... I'm a bit stumped. You could try from a different directory

Or you can simply download the all-in-one `portalocker.py` file from the releases: https://github.com/WoLpH/portalocker/releases/download/v1.7.0/portalocker.py

**Comment by MMK21Hub** [comment]
Weird.

Python doesn't seem to be able to import some of the other modules in portalocker.py either. (It can do things like `os` fine though.) Oh well. Thanks for your replies!
