### ISSUE TITLE
Distribution of `tests` in top level `site-packages`

### ISSUE THREAD

**Issue by vkomarov-r7** [WoLpH/portalocker#56]
Hello,

Based on our troubleshooting, we've found an issue with this package where the tests appear to be inadvertently shipped as part of the source distribution, and are put in the top level `python/3.x/site-packages/tests` folder. This is a problem for us during our test suite execution, as our imports are also located in a local folder called `tests`, but due to `sys.path` precedence, it appears that this package's tests are included as well.

If possible please change the installation of `tests` to no longer be installed in a top level directory. We are using this package via the `msal-extensions` package.

# Steps to Reproduce

1. Create a virtualenv: `python -m venv env`
2. Activate: `source env/bin/activate`
3. Install portalocker from PyPi: `pip install portalocker==1.7.0`
4. Navigate to `venv/lib/python3.x/site-packages/tests`
5. Observe all tests from `portalocker_tests` be present.

**Comment by WoLpH** [comment]
Very odd problem, the `.tar.gz` file doesn't contain the tests but the `.whl` does. Perhaps a remnant of when it was still named `tests` (which was changed a few versions ago)

I've released a new version and verified that they're really gone now :)
