### ISSUE TITLE
Declare PEP 561 compliance (type checking support)

### ISSUE THREAD

**Issue by BoniLindsley** [WoLpH/portalocker#60]
Type checkers do not yet know that `portalocker` now supports type checking.

Type hinting was recently add to this library, as of commit 41de2a09b6a2f52f2afe0a9dd0cc3a2f381046c0, or [version 2.1.0](https://github.com/WoLpH/portalocker/releases/tag/v2.1.0). (Good job on that. I was not expecting it to be added yet!) This means library users can run type checkers on their code against the types defined by the library. A simple usage example is as follows:

```sh
#!/usr/bin/env bash

# Make sure the current version has type hinting\.
python3 -m pip install portalocker>=2.1.0
# Create a file to use the library.
file=watchcat.py
echo import portalocker > $file
# Type check it.
mypy $file
```

### Expected and current behaviours

The type checking should pass, since the Python code only imports `portalocker`. The output I have, on Python 3.9.1, is instead

    watchcat.py:1: error: Skipping analyzing 'portalocker': found module but no type hints or library stubs
    watchcat.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
    Found 1 error in 1 file (checked 1 source file)

### Possible solution

Once a package has type hinting, it can inform type checkers by including a file name named `py.typed` in the installed package directory, as specified in [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information). (I only found out about this today.) In the case of this project, it is sufficient to

1.  Create the file `portalocker/py.typed`.
2.  Include this in `setup.py`: `package_data={'portalocker': ['py.typed']},`.

The following Python script should achieve this.

```py
#!/usr/bin/env python3

import pathlib

pathlib.Path('portalocker/py.typed').touch()
setup_path = pathlib.Path('setup.py')
with setup_path.open() as setup_file:
    lines = setup_file.readlines()
if not any('package_data' in line for line in lines):
    lines.insert(
        len(lines) - 1,
        "        package_data={'portalocker': ['py.typed']},\n",
    )
    with setup_path.open('w') as setup_file:
        lines = setup_file.writelines(lines)
```

Once patched and reinstalled, the `mypy` usage above should pass.

**Comment by WoLpH** [comment]
I didn't know about `py.typed` either, that's news to me :)
In any case, good idea. I'll add it to this library (and possibly a few others as well).

Due to the fragile nature of apple hardware my laptop is currently out of commission unfortunately, and that's the only system I've completely setup to properly create new releases with signing and everything so it'll probably take a few weeks until I can create a new release.

**Comment by BoniLindsley** [comment]
Thank you for adding this! Now I can have this in some commits!

```diff
-import portalocker  # type: ignore[import]
+import portalocker
```

There is one tinsy little issue I ran into when using the type hint -- the [exception base class](https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/exceptions.py#L5) is not type hinted. I think the following is sufficient to type hint it:

```diff
+import typing
+
+
class BaseLockException(Exception):
    # Error codes:
    LOCK_FAILED = 1

-    def __init__(self, *args, fh=None, **kwargs):
+    def __init__(
+        self,
+        *args: typing.Any,
+        fh: typing.Optional[typing.IO] = None,
+        **kwargs: typing.Any,
+    ) -> None:
        self.fh = fh
        Exception.__init__(self, *args, **kwargs)
```

That was the only one I ran into directly. Checking the package shows a few untyped functions. These are in `utils` though, so I am guessing these probably do not matter much for the users.

-   `portalocker.utils.coalesce(*args: typing.Any, test_value: typing.Any = None)`
    <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/utils.py#L31>
-   `portalocker.utils.LockBase._timeout_generator(self, timeout: float, check_interval: float)`
    <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/utils.py#L132>
-   `portalocker.utils.LockBase.__exit__(self, type_, value, tb)`: This one is a little more complicated, and requires extra imports, as suggested in <https://mypy.readthedocs.io/en/stable/protocols.html#contextmanager-t>
    <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/utils.py#L155>
-   I have not used `__delete__` before.
    <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/utils.py#L158>
-   `portalocker.utils.BoundedSemaphore.get_filename(self, number: int)`
    <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/utils.py#L389>

There are also two in the `redis` module, but I do not know enough about it to suggest anything, and the `redis-py` package does not seem to have type hints anyway.

-   <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/redis.py#L113>
-   <https://github.com/WoLpH/portalocker/blob/631352fbfd9f2b780a6d5f9da39646f4088910aa/portalocker/redis.py#L179>

**Comment by WoLpH** [comment]
I completely forgot to reply to this... obviously we've already had a few releases so it's definitely included but it's certainly not perfect yet. I've improved the type hints somewhat but I'm not at 100% coverage yet

Perhaps some day :)

Thank you for all the help @BoniLindsley!
