### ISSUE TITLE
Neither exclusive nor shared locks working as expected on Windows

### ISSUE THREAD

**Issue by parkournerd** [WoLpH/portalocker#63]
Morning!

I am trying to use portalocker for some system-wide resource management under Windows.
When I run either of the following from two different programs:
`portalocker.lock(fileHandle, portalocker.LOCK_EX)`
Or
`portalocker.lock(fileHandle, portalocker.LOCK_SH)`

I always get the following on the second program:
"LockException: (1, 'The process cannot access the file because another process has locked a portion of the file.')"

My expectation was that exclusive lock is a write lock and the shared lock is a read lock, but instead both:
- exhibit exclusive locking in Python
- when locked:
  - can be read from notepad
  - cannot be written from notepad
  - cannot be moved from file explorer

**Comment by WoLpH** [comment]
The problem with locking mechanisms is that they need to be implemented in the same way by all participating applications. So the big question is... which locking mechanism is notepad/file explorer using.

Apparently there are multiple locking mechanisms on Windows: https://github.com/WoLpH/portalocker/issues/58

**Comment by parkournerd** [comment]
That makes sense for observations with notepad and file explorer. I see PL uses two methods.

As for the shared lock, the confusion was that I thought it was like a sempahore.

Thank you!
