### ISSUE TITLE
is lock reenterable?

### ISSUE THREAD

**Issue by SenjuObito** [WoLpH/portalocker#72]
with portalocker.Lock("temp", flags=portalocker.LOCK_EX) as fd:
    print("locked")
    with portalocker.Lock("temp", flags=portalocker.LOCK_EX):
        print("reentrant")
        input()
i made a test, found portalocker is not reenterable. Does portalocker support reentrant?

**Comment by WoLpH** [comment]
No, the locks are not reentrant because that is usually not what you would want to happen.

If it would be reentrant and you would try to write from multiple threads, it would succeed but could easily give you the wrong results. You can pass around the original lock however.

**Comment by WoLpH** [comment]
I forgot to mention... there is RLock which is reentrant :)
https://portalocker.readthedocs.io/en/latest/portalocker.html?highlight=rlock#portalocker.RLock
