### ISSUE TITLE
What is the actual license for this project?

### ISSUE THREAD

**Issue by dssd96** [WoLpH/portalocker#79]
The [license file](https://github.com/WoLpH/portalocker/blob/8b6456dbc26a099f9bd705cc7f30ec8e08f6a0d6/LICENSE) contains a copy of the "PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2" text. Therein, the word "Python" appears as the name of "the software", but this is not really referring to this project. Should the name "Python" maybe changed to the module name?

**Comment by WoLpH** [comment]
You're right, that's a bit confusing. I've updated the license to the 3-clause BSD license which is effectively the same but doesn't include the PSF references
