### ISSUE TITLE
fileno support

### ISSUE THREAD

**Issue by mockodin** [WoLpH/portalocker#80]
fcntl supports passing the fileno directly, this seems like it should be supportable here as well

```
fh = open(filename, "w")
fcntl.flock(fh.fileno(), fcntl.LOCK_EX)
```

**Comment by WoLpH** [comment]
I can add partial support. On posix systems this is indeed possible, on windows systems it is not :)

**Comment by WoLpH** [comment]
Release 2.6.0 supports `fh.fileno()` as well on posix (i.e. linux/unix/osx) systems
