### ISSUE TITLE
Mismatch between documentation and implementation

### ISSUE THREAD

**Issue by clo-vis** [wolph/portalocker#82]
The documentation of class Lock states:
> truncate: use truncate to emulate 'w' mode, None is disabled, 0 is truncate to 0 bytes

and later:

> Note that the file is opened first and locked later. So using 'w' as  mode will result in truncate _BEFORE_ the lock is checked.

There is, however, no argument _truncate_, and self.truncate is set to _True_ if _mode_ contains _w_.

**Comment by clo-vis** [comment]
(flags is also missing in the documentation)

**Comment by wolph** [comment]
I'm not entirely sure where or how this originated, but the truncate is only added through `mode='w'`. I suppose I could add a `truncate` argument which overwrites the `mode` behaviour :)

**Comment by wolph** [comment]
Instead of adding a new state with ambiguous behaviour depending on `mode`, I've removed the `truncate` flag from the documentation and expanded the `mode` documentation.
