### ISSUE TITLE
Python 3.12: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by hugovk** [wolph/portalocker#86]
The [second and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

The full release is expected in 3 weeks: 2023-10-02

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

---

However, when adding 3.12 to the CI like https://github.com/hugovk/portalocker/commit/ce601ff5dec23b5abe380be956945b802e0f4464, it [fails](https://github.com/hugovk/portalocker/actions/runs/6150722558/job/16689374543) with:

```pytb
def test_combined(tmpdir):
>       from distutils import dist
E       ModuleNotFoundError: No module named 'distutils'
```

---

This will be due to the `distutils` changes in Python 3.12:

> `easy_install`, `pkg_resources`, `setuptools` and `distutils` are no longer provided by default in environments created with `venv` or bootstrapped with `ensurepip`, since they are part of the setuptools package. For projects relying on these at runtime, the `setuptools` project should be declared as a dependency and installed separately (typically, using pip).

https://docs.python.org/3.12/whatsnew/3.12.html#removed

**Comment by wolph** [comment]
I'm currently working on a big overhaul of one of my other packages (https://github.com/wolph/python-progressbar) and with that I'm working on converting all of my projects to a PEP517 compliant `pyproject.toml` file so this issue will be gone soon :)

Thank you for letting me know, it looks like I might have quite a few packages that I need to rework the coming week.

**Comment by wolph** [comment]
I've created a new release that has this issue completely fixed :)
