### ISSUE TITLE
Require explicit name for BoundedSemaphore()?

### ISSUE THREAD

**Issue by dhoulder** [wolph/portalocker#87]
Say there are two unrelated applications on the same host, and they both use the default ``name`` for ``BoundedSemaphore()``.

For example:
```
semaphore = portalocker.BoundedSemaphore(n)
```

Won't they both try and use the same set of lock files and interfere with each other?

To ensure backwards compatibility,  you could create a new class ``NamedBoundedSemaphore`` with a required name argument and deprecate ``BoundedSemaphore``

**Comment by wolph** [comment]
You are largely correct but you've glossed over a small detail, the directory is randomized by the `tempfile.gettempdir()` function: https://github.com/wolph/portalocker/blob/ea5e1809e28d9197aaea22c4bbefe1dae2bcaef4/portalocker/utils.py#L430-L449

In practice you will never have 2 unrelated applications colliding :)

**Comment by dhoulder** [comment]
``tempfile.gettempdir()`` always returns ``/tmp`` for me (Ubuntu, not setting TMPDIR, TEMP or TMP). See https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir 
```
>>> import tempfile
>>> tempfile.gettempdir()
'/tmp'
```

**Comment by wolph** [comment]
Oops... in that case I have made a wrong assumption a long time ago and created a semaphore that could cause issues in some cases.

I'm in the process of creating a new release anyhow so I'll make sure to add your suggested `NamedBoundedSemaphore` class

**Comment by dhoulder** [comment]
No worries. Happens to the best of us :smile: 
Thanks for all your hard work.

**Comment by wolph** [comment]
As a backstory, I'm guessing this made me think it was random. On my laptop I get this:
```>>> import tempfile
>>> tempfile.gettempdir()
'/var/folders/y7/n86bj8vn48vftzwyzdwdpvtc0000gn/T'
```

Seemed pretty random to me ;)

**Comment by dhoulder** [comment]
Hmm… Is that inside some kind of container or WSL on Windows or something?

**Comment by wolph** [comment]
No... that's on OS X

**Comment by dhoulder** [comment]
OK, so that seems to be a per-user $TMPDIR. I think my original observation mostly still holds: Two unrelated applications running as the same user on the same host could interfere with each other.

**Comment by wolph** [comment]
Your observation is correct indeed. If I start 2 completely unrelated applications I get the same results.

Furthermore:
```$ echo $TMPDIR
/var/folders/y7/n86bj8vn48vftzwyzdwdpvtc0000gn/T/```

I really should have read the Python manual, it's pretty clear about this :X
