### ISSUE TITLE
docs files are installed in the wrong location

### ISSUE THREAD

**Issue by hubutui** [wolph/portalocker#88]
portalocker 2.8.0
docs files are installed in the wrong location:

```bash
python-portalocker: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.opt-1.pyc exists in filesystem (owned by python-pipenv)
python-portalocker: /usr/lib/python3.11/site-packages/docs/__pycache__/conf.cpython-311.pyc exists in filesystem (owned by python-pipenv)
python-portalocker: /usr/lib/python3.11/site-packages/docs/conf.py exists in filesystem (owned by python-pipenv)
```
Maybe we should exclude `docs`, or install them to `site-packages/portalocker/docs`?

**Comment by wolph** [comment]
Oops... I just upgraded to a new build system and forgot to include that. Good catch! I've created a new release which shouldn't have the docs anymore :)

**Comment by hubutui** [comment]
I just download and install the wheel file from [here](https://github.com/wolph/portalocker/releases/download/v2.8.1/portalocker-2.8.1-py3-none-any.whl), and `pip show --files portalocker` shows:
```text
Files:
  dist/__pycache__/portalocker-2.7.0.cpython-311.pyc
  dist/__pycache__/portalocker-2.8.0.cpython-311.pyc
  dist/portalocker-2.7.0.py
  dist/portalocker-2.8.0.py
  docs/_theme/__pycache__/flask_theme_support.cpython-311.pyc
  docs/_theme/flask_theme_support.py
```

**Comment by hubutui** [comment]
If I download the [source tarball](https://github.com/wolph/portalocker/archive/refs/tags/v2.8.1.tar.gz), and build it with:
```bash
 python -m build --wheel --no-isolation
```
and then install the wheel file. `pip show --files portalocker` shows:
```text
Files:
  docs/_theme/__pycache__/flask_theme_support.cpython-311.pyc
  docs/_theme/flask_theme_support.py
```

`docs` are still installed to site-packages.

**Comment by wolph** [comment]
You're right... it seems that excluding `docs` or `docs*` does not exclude `docs/_theme` :(

I've created yet another release, this time only explicitly including the package and ignoring everything else.

**Comment by wolph** [comment]
Thank you for letting me know!
